Update service-settings.js
When attempting to add a new e-mail service I am presented with the following error:
`TypeError: elements.each is not a function service-settings.js:37:9.`

It would appear that the root cause was an attempt to call a method .each() which doesn't exist on vanilla javascript array objects, whereas this is a valid jQuery method.

The above code change addresses this problem.